num_classes: 6 # Number of classes in the dataset
image_dimensions: [384, 576] # Image dimensions
batch_size: 25 # Batch size
num_epochs: 200 # Number of epochs for training
model_path: "models/final_model.pt" # Path to the trained model file
num_samples: 1 # Number of samples to find
num_workers: 4 # Number of workers for data loading
zone_type: "marker" # Type of zone to predict
view_mode: "bottom" # View mode for point finding
num_points: 30 # Number of points to find on predicted segmentation mask for each different mask

lr: 0.001 # Learning rate for Adam
weight_decay: 0.0001 # Weight decay for Adam
factor: 0.1 # Factor for learning rate for ReduceLROnPlateau
patience: 10 # Patience for learning rate for ReduceLROnPlateau
min_lr: 0.000001 # Minimum learning rate for ReduceLROnPlateau

early_stopping_patience: 20 # Patience for early stopping

# Color map for visualization
cmap:
  - [150, 24, 0]     # Class 0: Остальное (Other)
  - [119, 221, 119]  # Class 1: Зоны посадки (Landing Zones)
  - [58, 117, 196]   # Class 2: Вода (Water)
  - [255, 153, 0]    # Class 3: Дороги (Roads)
  - [255, 239, 213]  # Class 4: Движущиеся объекты (Moving Objects)
  - [128, 128, 128]  # Class 5: Маркер (Marker)

# Dataset information
datasets:
  - name: "semantic_drone_dataset"
    img_path: "datasets/DroneSemantic/img/"
    mask_path: "datasets/DroneSemantic/mask/"
    class_mapping:
        0: 0
        1: 3
        2: 1
        3: 1
        4: 1
        5: 2
        6: 0
        7: 0
        8: 0
        9: 0
        10: 0
        11: 0
        12: 0
        13: 0
        14: 0
        15: 4
        16: 4
        17: 4
        18: 4
        19: 0
        20: 0
        21: 5
        22: 0
        23: 0
    mask_type: "grayscale"
  - name: "swiss_okuna"
    img_path: "datasets/SwissOkuna/img"
    mask_path: "datasets/SwissOkuna/mask"
    class_mapping:
        0: 1
        1: 0
        2: 0
        3: 3
        4: 1
        5: 0
        6: 0
        7: 4
        8: 2
        9: 4
    mask_type: "grayscale"
