seed: 42 # Seed for reproducibility
num_classes: 6 # Number of classes in the dataset
image_dimensions: [384, 576] # Image dimensions
batch_size: 10 # Batch size
num_epochs: 200 # Number of epochs for training
model_path: "models/final_model.pt" # Path to the trained model file
num_samples: 3 # Number of samples to plot in evaluation and point-finding
num_workers: 4 # Number of workers for data loading
zone_type: "marker" # Type of zone to predict
view_mode: "bottom" # View mode for point finding
num_points: 30 # Number of points to find on predicted segmentation mask for each different mask

lr: 0.001 # Learning rate for Adam
weight_decay: 0.0001 # Weight decay for Adam
factor: 0.1 # Factor for learning rate for ReduceLROnPlateau
patience: 10 # Patience for learning rate for ReduceLROnPlateau
min_lr: 0.000001 # Minimum learning rate for ReduceLROnPlateau

early_stopping_patience: 20 # Patience for early stopping

# Color map for visualization
cmap:
  - [150, 24, 0]     # Class 0: Other / Obstacles
  - [119, 221, 119]  # Class 1: Landing Zones
  - [58, 117, 196]   # Class 2: Water
  - [255, 153, 0]    # Class 3: Roads
  - [255, 239, 213]  # Class 4: Moving Objects
  - [128, 128, 128]  # Class 5: Marker

# Dataset information
datasets:
  - name: "semantic_drone_dataset"
    img_path: "datasets/DroneSemantic/img/"
    mask_path: "datasets/DroneSemantic/mask/"
    class_mapping:
      0: 0 # unlabeled --> Other
      1: 3 # paved-area --> Roads
      2: 1 # dirt --> Landing Zones
      3: 1 # grass --> Landing Zones
      4: 1 # gravel --> Landing Zones
      5: 2 # water --> Water
      6: 0 # rocks --> Other
      7: 0 # pool --> Other
      8: 0 # vegetation --> Other
      9: 0 # roof --> Other
      10: 0 # wall --> Other
      11: 0 # window --> Other
      12: 0 # door --> Other
      13: 0 # fence --> Other
      14: 0 # fence-pole --> Other
      15: 4 # person --> Moving Objects
      16: 4 # dog --> Moving Objects
      17: 4 # car --> Moving Objects
      18: 4 # bicycle --> Moving Objects
      19: 0 # tree --> Other
      20: 0 # bald-tree --> Other
      21: 5 # ar-marker --> Marker
      22: 0 # obstacle --> Other
      23: 0 # conflicting --> Other
  - name: "swiss_okuna"
    img_path: "datasets/SwissOkuna/img"
    mask_path: "datasets/SwissOkuna/mask"
    class_mapping:
      0: 1 # background --> Landing Zones
      1: 0 # outdoor structures --> Other
      2: 0 # buildings --> Other
      3: 3 # paved ground --> Roads
      4: 1 # non-paved ground --> Landing Zones
      5: 0 # train tracks --> Other
      6: 0 # plants --> Other
      7: 4 # wheeled vehicles --> Moving Objects
      8: 2 # water --> Water
      9: 4 # people --> Moving Objects
  - name: "aeroscapes"
    img_path: "datasets/Aeroscapes/img"
    mask_path: "datasets/Aeroscapes/mask"
    class_mapping:
      0: 4 # person --> Moving Objects
      1: 4 # bike --> Moving Objects
      2: 4 # car --> Moving Objects
      3: 4 # drone --> Moving Objects
      4: 4 # boat --> Moving Objects
      5: 4 # animal --> Moving Objects
      6: 0 # obstacle --> Other
      7: 0 # construction --> Other
      8: 0 # vegetation --> Other
      9: 3 # road --> Roads
      10: 0 # sky --> Other
      "placeholder_class": 1 # Placeholder class for unlabeled data
